const players = [
  { id: 1, name: "鸽子", 
    games: ["永劫无间","steam热门游戏"], 
    styles: ["青叔音", "娱乐局", "不压力"], 
    orders: ["永劫无间技术","steam热门游戏"], 
    tier: "技术", avatar: "./avatars/gezi.jpg", 
    signature: "泥真的要点一单客服嘛", 
    description: "主玩永劫无间三排天选模式，擅长长剑+阔刀，团队意识拉满。语音成熟稳重，心态好不压力，带你稳定吃鸡。", 
    availableTime: "每日 18:00 - 02:00", 
    audio: "./audio/gezi.mp3", 
    weeklyOrders: 45, rating: 98 },
  { id: 2, 
    name: "雨眠", 
    games: ["永劫无间"], 
    styles: ["萝莉音", "温柔音", "娱乐局"], 
    orders: ["永劫无间娱乐"], 
    tier: "娱乐", 
    avatar: "./avatars/yumian.jpg", 
    signature: "甜萌萝莉音，双区娱乐全程陪", 
    description: "永劫无间主玩玉玲珑/殷紫萍，声音软萌，会撒娇会鼓励，陪玩体验拉满，会配合会拉扯，情绪稳定，温柔的情绪树洞", 
    availableTime: "每日 21:00 - 6:00", 
    audio: "./audio/yumian.mp3", 
    weeklyOrders: 38, rating: 99 },
  { id: 3, 
    name: "QQ", 
    games: ["永劫无间"], 
    styles: ["御姐音", "娱乐局", "不压力"], 
    orders: ["永劫无间娱乐"], 
    tier: "娱乐", 
    avatar: "./avatars/qq.jpg", 
    signature: "永劫无间娱乐御姐音，边玩边聊超快乐", 
    description: "永劫无间三排/单排皆可，主打轻松愉快的陪伴体验。熟练胡桃/无尘，治疗与支援到位。陪你唠嗑、听歌、下饭，气氛活跃不冷场。", 
    availableTime: "每日 19:00 - 01:00", 
    audio: "./audio/qq.mp3", 
    weeklyOrders: 32, rating: 96 },
  { id: 4, 
    name: "巴掌印", 
    games: ["无畏契约","永劫无间","三角洲行动","steam热门游戏"], 
    styles: ["御姐音", "娱乐局"], 
    orders: ["永劫无间娱乐","无畏契约娱乐", "三角洲机密娱乐","steam热门游戏"], 
    tier: "娱乐", 
    avatar: "./avatars/bazhangyin.jpg", 
    signature: "三区全能御姐，瓦洲机密向导", 
    description: "心态好脾气好不矫情，无敌尬聊王，偶尔小c ，瓦除一突所有位置可补，洲主玩支援/信息，对枪打得过保护你，打不过保佑你，劫主二号位/三号位，老板指哪打哪绝对听从老板指挥! ", 
    availableTime: "全天可约", 
    audio: "./audio/bazhangyin.mp3", 
    weeklyOrders: 52, rating: 99 },
  { id: 5, 
    name: "小白", 
    games: ["三角洲行动"], 
    styles: ["萝莉音", "娱乐局", "温柔音"], 
    orders: ["三角洲机密娱乐"], 
    tier: "娱乐", 
    avatar: "./avatars/xiaobai.jpg", 
    signature: "三角洲小白妹妹，机密行动安全撤离专家", 
    description: "三角洲行动主玩医疗+支援兵种，熟悉机密地图。会帮你搜刮物资、规划撤离路线、危险时第一时间救援。语音软萌，陪玩体验超舒适。", 
    availableTime: "不固定时间", 
    audio: "./audio/xiaobai.mp3", 
    weeklyOrders: 28, rating: 98 },
  { id: 6, 
    name: "临沐", 
    games: ["无畏契约", "三角洲行动","steam热门游戏"], 
    styles: ["青叔音", "纯武将"], 
    orders: ["无畏契约娱乐", "三角洲绝密技术","steam热门游戏"], 
    tier: "金牌", 
    avatar: "./avatars/linmu.jpg", 
    signature: "三角洲全能补位，瓦区哨位精通", 
    description: "无畏契约主玩哨位，残局兜底的神。三角洲主玩一号位，先打懦夫后打药，二字欧美一字猖！", 
    availableTime: "每日 20:00 - 03:00", 
    audio: "./audio/linmu.mp3",
    weeklyOrders: 41, rating: 99 },
  { id: 7, 
    name: "阿鹤", 
    games: ["永劫无间", "三角洲行动","steam热门游戏"], 
    styles: ["温柔音","教学型","不压力"], 
    orders: ["永劫无间娱乐", "三角洲绝密技术","steam热门游戏"], 
    tier: "金牌", 
    avatar: "./avatars/ahe.jpg", 
    signature: "永劫变身拆火，三角洲全能干员，稳中带秀", 
    description: "永劫无间主玩变身系英雄（大佛、沈妙、岳山），三角洲全干员教学。全点位教学，全地图教学，猛攻跑刀，全局思路教学，全玩法教学，大红刷新点位，房卡点位教学。团队型选手，稳中带秀，能抗能打能策应。", 
    availableTime: "每日 18:00 - 23:59", 
    audio: "./audio/ahe.mp3", 
    weeklyOrders: 65, rating: 99 },
  { id: 8, 
    name: "小憋", 
    games: ["永劫无间"], 
    styles: ["极品破碎屌丝音", "战斗型", "上分"], 
    orders: ["永劫无间技术"], 
    tier: "魔王", 
    avatar: "./avatars/xiaobie.jpg", 
    signature: "想不想看看火男玩家们在干什么", 
    description: "永劫无间单排天人前百，你的三排v2狂战火老公", 
    availableTime: "每日 21:00 - 06:00", 
    audio: "./audio/xiaobie.mp3", 
    weeklyOrders: 48, rating: 99 },
  { id: 9, 
    name: "莫遮", 
    games: ["永劫无间", "三角洲行动","steam热门游戏"], 
    styles: ["咖啡因", "温柔音"], 
    orders: ["永劫无间娱乐", "三角洲机密娱乐"], 
    tier: "娱乐", 
    avatar: "./avatars/mozhe.jpg", 
    signature: "双区娱乐+机密，节奏稳心态好", 
    description: "永劫主玩岳山，给队友配合。三角洲主玩信息位，熟悉机密各地图打法思路。心态好，爆点沟通积极。", 
    availableTime: "每日 16:00 - 00:00", 
    audio: "./audio/mozhe.mp3", 
    weeklyOrders: 30, rating: 95 },
  { id: 10, 
    name: "楠平", 
    games: ["永劫无间"], 
    styles: ["青年音", "不压力", "娱乐局"], 
    orders: ["永劫无间娱乐"], 
    tier: "娱乐", 
    avatar: "./avatars/nanping.jpg", 
    signature: "永劫无间美人鱼叔叔，陪你聊陪你玩", 
    description: "永劫无间娱乐局常客，熟悉所有英雄。主打陪伴氛围，节奏轻松，边打边唠嗑。适合想放松、找个搭子聊天开黑的玩家。", 
    availableTime: "每日 13:00 - 23:00", 
    audio: "./audio/nanping.mp3", 
    weeklyOrders: 35, rating: 97 },
  { id: 11, 
    name: "丸子", 
    games: ["无畏契约", "三角洲行动","steam热门游戏"], 
    styles: ["少女音", "娱乐局", "温柔音"], 
    orders: ["无畏契约娱乐", "三角洲机密娱乐","steam热门游戏"], 
    tier: "娱乐", 
    avatar: "./avatars/wanzi.jpg", 
    signature: "瓦洲双修，元气少女", 
    description: "无畏契约主玩烟位、哨位，三角洲主玩蜂医、麦晓雯（喜欢跑刀的囤囤鼠一枚呀），元气少女音，活泼嘴甜有分寸", 
    availableTime: "每日 15:00 - 01:00", 
    audio: "./audio/wanzi.mp3", 
    weeklyOrders: 56, rating: 100 },
  { id: 12, 
    name: "小波", 
    games: ["永劫无间"], 
    styles: ["青年音", "娱乐局", "不压力"], 
    orders: ["永劫无间娱乐"], 
    tier: "娱乐", 
    avatar: "./avatars/xiaobo.jpg", 
    signature: "劫区快乐小波，下饭操作超有梗", 
    description: "永劫无间娱乐局常驻，主玩各种冷门英雄也能秀。操作飘逸，话痨会整活，一把游戏笑点不断，适合想开心放松的你。", 
    availableTime: "每日 17:00 - 02:00",
    audio: "./audio/xiaobo.mp3", 
    weeklyOrders: 26, rating: 95 },
  { id: 13, 
    name: "三笠", 
    games: ["无畏契约"], 
    styles: ["青叔音", "娱乐局", "不压力"], 
    orders: ["无畏契约娱乐"], 
    tier: "娱乐", 
    avatar: "./avatars/sanli.jpg", 
    signature: "瓦区休闲搭子，娱乐排位两不误", 
    description: "无畏契约位置全能，缺什么补什么。擅长分析对方敌人，处理与信息沟通。节奏不紧不慢，陪您一局接一局，有唱歌才艺。", 
    availableTime: "每日 18:00 - 00:00", 
    audio: "./audio/sanli.mp3", 
    weeklyOrders: 33, rating: 97 },
  { id: 14, 
    name: "苹果", 
    games: ["永劫无间"], 
    styles: ["青叔音", "指挥型", "上分"], 
    orders: ["永劫无间技术"], 
    tier: "技术", 
    avatar: "./avatars/pingguo.jpg", 
    signature: "主战马会球弓三排国服刘炼，可教学，克烈小迷弟", 
    description: "十分温柔从不压力人（不破防）可指挥的打，主玩三排想提升三排存活能力、思路、伤害、奶量、拉扯的可以边打边教学", 
    availableTime: "每日 12:00 - 23:59", 
    audio: "./audio/pingguo.mp3", weeklyOrders: 39, rating: 98 },
  { id: 15, 
    name: "小运", 
    games: ["永劫无间"], 
    styles: ["青年音", "战斗型", "指挥型"], 
    orders: ["永劫无间技术"], 
    tier: "技术", 
    avatar: "./avatars/xiaoyun.jpg", 
    signature: "国服沙男，单排导师精通蓝白博弈", 
    description: "永劫无间国服前100，精通双截棍，长棍，太刀，会抖枪术一些技巧。适合想冲段位、学英雄的玩家。", 
    availableTime: "每日 20:00 - 02:00", 
    audio: "./audio/xiaoyun.mp3", 
    weeklyOrders: 37, rating: 99 },
  { id: 16, 
    name: "礼拜六", 
    games: ["无畏契约","永劫无间","三角洲行动","steam热门游戏"], 
    styles: ["青年音", "不压力"], 
    orders: ["永劫无间娱乐","无畏契约技术", "三角洲机密娱乐","steam热门游戏"], 
    tier: "技术", 
    avatar: "./avatars/libailiu.jpg", 
    signature: "永劫冰女狐狸，瓦霓虹，三角洲张姐。话多不高冷，打得过我的不多，打不过我的懒得打", 
    description: "永劫冰女狐狸控场拉扯，瓦霓虹跑轰突破，三角洲张姐正面硬刚，每款都有绝活。话多不冷场，素质高不压力，输了复盘不甩锅。至于那些打不过我的——我更是懒得打", 
    availableTime: "每日 14:00 - 23:00", 
    audio: "./audio/libailiu.mp3", 
    weeklyOrders: 50, rating: 99 },
  { id: 17, 
    name: "蝴蝶湖", 
    games: ["永劫无间"], 
    styles: ["青年音", "不压力"], 
    orders: ["永劫无间技术"], 
    tier: "金牌", 
    avatar: "./avatars/hudiehu.jpg", 
    signature: "永劫无间陪练，段位代打｜，高效上分，技术娱乐都可以", 
    description: "永劫无间排位上分、可接单排、三排、双排陪，沟通顺畅。", 
    availableTime: "每日 16:00 - 23:59", 
    audio: "./audio/hudiehu.mp3", 
    weeklyOrders: 43, rating: 98 },
  { id: 18, 
    name: "小予", 
    games: ["永劫无间"], 
    styles: ["极品屌丝音", "武将"], 
    orders: ["永劫无间技术"], 
    tier: "技术", 
    avatar: "./avatars/xiaoyu1.jpg", 
    signature: "永劫全部英雄都略懂一点 刀房选手", 
    description: "永劫全部英雄都略懂一点 刀房选手 老板有不服的人也可以点我帮打的 纯武将 落地架运营都可以打-斩你无需第二剑 豪你无需第二遍", 
    availableTime: "每日 21:00 - 03:00", 
    audio: "./audio/xiaoyu1.mp3", 
    weeklyOrders: 45, rating: 98 },


    
];
